--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Muqsit/Tebex
build-by-default: true
branches:
  - master
  - pmmp-api4
  - pmmp-api5
projects:
  Tebex:
    path: ""
    libs:
      - src: muqsit/tebexapi/TebexApi
        version: ^0.1.0
...